version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hockey_blast_app
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"
      - "8001:8001"

  db:
    image: postgres:13
    container_name: hockey_blast_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.common_lib_for_docker_db_restore:/sample_db_restore
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5433:5432" # Map port 5433 on the host to port 5432 in the container
    depends_on:
      - app # Dependency is here just to pull the sample DB backup from the app container (from the hochey-blast-common-lib dependency)
