version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hockey_blast_app
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: hockey_blast_db
    environment:
      POSTGRES_USER: frontend_user
      POSTGRES_PASSWORD: hockey-blast
      POSTGRES_DB: hockey_blast
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
