version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hockey_blast_app
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: hockey_blast_db
    environment:
      POSTGRES_USER: frontend_user
      POSTGRES_PASSWORD: hockey-blast
      POSTGRES_DB: hockey_blast
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./sample_db_backup.sql:/docker-entrypoint-initdb.d/sample_db_backup.sql
    ports:
      - "5433:5432" # Map port 5433 on the host to port 5432 in the container
    command: [ "sh", "-c", "docker-entrypoint.sh postgres && /docker-entrypoint-initdb.d/init_db.sh" ]

volumes:
  postgres_data:
