"""Add stats table DivisionStatsHuman

Revision ID: 0af69f2d2746
Revises: c26c5fb00f6b
Create Date: 2024-12-19 13:32:04.569215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af69f2d2746'
down_revision = 'c26c5fb00f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_division_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('penalty_minutes', sa.Integer(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('penalty_minutes_per_game', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'human_id', 'division_id', name='_org_human_division_uc')
    )
    with op.batch_alter_table('human_division_stats', schema=None) as batch_op:
        batch_op.create_index('idx_division_assists_per_game', ['division_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_division_goals_per_game', ['division_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_division_penalty_minutes_per_game', ['division_id', 'penalty_minutes_per_game'], unique=False)
        batch_op.create_index('idx_division_points_per_game', ['division_id', 'points_per_game'], unique=False)
        batch_op.create_index('idx_org_assists_per_game', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_org_games_played', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_goals_per_game', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_penalty_minutes_per_game', ['org_id', 'penalty_minutes_per_game'], unique=False)
        batch_op.create_index('idx_org_points_per_game', ['org_id', 'points_per_game'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_division_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_org_points_per_game')
        batch_op.drop_index('idx_org_penalty_minutes_per_game')
        batch_op.drop_index('idx_org_goals_per_game')
        batch_op.drop_index('idx_org_games_played')
        batch_op.drop_index('idx_org_assists_per_game')
        batch_op.drop_index('idx_division_points_per_game')
        batch_op.drop_index('idx_division_penalty_minutes_per_game')
        batch_op.drop_index('idx_division_goals_per_game')
        batch_op.drop_index('idx_division_assists_per_game')

    op.drop_table('human_division_stats')
    # ### end Alembic commands ###
