"""Remove FK from level_id in Division in preparation of table renaming

Revision ID: 112494871c38
Revises: fde4ebac8df2
Create Date: 2024-12-11 12:58:10.129790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112494871c38'
down_revision = 'fde4ebac8df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_constraint('divisions_level_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_foreign_key('divisions_level_id_fkey', 'levels', ['level_id'], ['id'])

    # ### end Alembic commands ###
