"""add helper class OrgLeagueSeasonDates

Revision ID: 1240e0a59abd
Revises: d89205a1ad44
Create Date: 2024-12-11 16:14:52.507191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1240e0a59abd'
down_revision = 'd89205a1ad44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_league_season_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('league_number', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'league_number', 'season_number', name='_org_league_season_uc_too')
    )
    op.create_table('names_in_org_league_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_league_season_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['org_league_season_id'], ['org_league_season_dates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_league_season_id', 'first_name', 'middle_name', 'last_name', name='_org_league_season_name_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names_in_org_league_season')
    op.drop_table('org_league_season_dates')
    # ### end Alembic commands ###
