"""add alias to Org

Revision ID: 1af00956dd02
Revises: dc2d126fa0e7
Create Date: 2024-12-11 13:47:00.318961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af00956dd02'
down_revision = 'dc2d126fa0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['alias'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
