"""Penalties instead of penalty minutes in  DivisionStatsHuman

Revision ID: 244c8fb749a0
Revises: 0af69f2d2746
Create Date: 2024-12-19 13:43:58.638049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244c8fb749a0'
down_revision = '0af69f2d2746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_division_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penalties_per_game', sa.Float(), nullable=True))
        batch_op.drop_index('idx_division_penalty_minutes_per_game')
        batch_op.drop_index('idx_org_penalty_minutes_per_game')
        batch_op.create_index('idx_division_penalties_per_game', ['division_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_penalties_per_game', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.drop_column('penalty_minutes_per_game')
        batch_op.drop_column('penalty_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_division_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('penalty_minutes_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_org_penalties_per_game')
        batch_op.drop_index('idx_division_penalties_per_game')
        batch_op.create_index('idx_org_penalty_minutes_per_game', ['org_id', 'penalty_minutes_per_game'], unique=False)
        batch_op.create_index('idx_division_penalty_minutes_per_game', ['division_id', 'penalty_minutes_per_game'], unique=False)
        batch_op.drop_column('penalties_per_game')
        batch_op.drop_column('penalties')

    # ### end Alembic commands ###
