"""add org to game

Revision ID: 2d83134aeef0
Revises: 47757ec44698
Create Date: 2024-12-11 12:18:32.225290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d83134aeef0'
down_revision = '47757ec44698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('games_game_number_key', type_='unique')
        batch_op.create_unique_constraint('_org_game_number_uc', ['org_id', 'game_number'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_org_game_number_uc', type_='unique')
        batch_op.create_unique_constraint('games_game_number_key', ['game_number'])
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
