"""Add org id to Level to test it

Revision ID: 392cea1da5ca
Revises: ed08dbe37cd5
Create Date: 2024-12-10 21:45:58.141813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392cea1da5ca'
down_revision = 'ed08dbe37cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_org_level_name_uc', ['org_id', 'level_name'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_org_level_name_uc', type_='unique')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
