"""org_id not null in Game

Revision ID: 449ae96da2e7
Revises: 570721039a08
Create Date: 2024-12-15 12:53:21.908095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449ae96da2e7'
down_revision = '570721039a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
