"""add org to division

Revision ID: 47757ec44698
Revises: a383ee9d7d1f
Create Date: 2024-12-11 12:16:04.286069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47757ec44698'
down_revision = 'a383ee9d7d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('_org_league_season_level_uc', ['org_id', 'league_number', 'season_number', 'level_id'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_org_league_season_level_uc', type_='unique')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
