"""Add first/last game id to all base stats classes

Revision ID: 4a4c701f0c94
Revises: 7f541e4b0bed
Create Date: 2024-12-25 23:18:54.582909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4c701f0c94'
down_revision = '7f541e4b0bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('division_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])

    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'games', ['first_game_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['last_game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_game_id')
        batch_op.drop_column('first_game_id')

    # ### end Alembic commands ###
