"""Add scorekeeper  stats

Revision ID: 65d87aa77dfe
Revises: dcb2ba88f1dd
Create Date: 2024-12-22 16:09:00.547842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d87aa77dfe'
down_revision = 'dcb2ba88f1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_stats_scorekeeper',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_recorded', sa.Integer(), nullable=True),
    sa.Column('sog_given', sa.Integer(), nullable=True),
    sa.Column('sog_per_game', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_uc_scorekeeper1')
    )
    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_org_games_recorded1', ['org_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_org_sog_given1', ['org_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_org_sog_per_game1', ['org_id', 'sog_per_game'], unique=False)

    op.create_table('division_stats_scorekeeper',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_recorded', sa.Integer(), nullable=True),
    sa.Column('sog_given', sa.Integer(), nullable=True),
    sa.Column('sog_per_game', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_uc_scorekeeper1')
    )
    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_division_games_recorded1', ['division_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_division_sog_given1', ['division_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_division_sog_per_game1', ['division_id', 'sog_per_game'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_division_sog_per_game1')
        batch_op.drop_index('idx_division_sog_given1')
        batch_op.drop_index('idx_division_games_recorded1')

    op.drop_table('division_stats_scorekeeper')
    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_org_sog_per_game1')
        batch_op.drop_index('idx_org_sog_given1')
        batch_op.drop_index('idx_org_games_recorded1')

    op.drop_table('org_stats_scorekeeper')
    # ### end Alembic commands ###
