"""league_number not unique any more in leagues

Revision ID: 65f0e6a4787e
Revises: 6e0bca999e31
Create Date: 2024-12-10 22:52:43.871383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f0e6a4787e'
down_revision = '6e0bca999e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint('leagues_league_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_unique_constraint('leagues_league_number_key', ['league_number'])

    # ### end Alembic commands ###
