"""Add OrgStatsSkater

Revision ID: 6c414a0e3751
Revises: e5c82c1106e0
Create Date: 2024-12-21 17:44:04.026861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c414a0e3751'
down_revision = 'e5c82c1106e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skater_org_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_uc2')
    )
    with op.batch_alter_table('skater_org_stats', schema=None) as batch_op:
        batch_op.create_index('idx_org_assists_per_game2', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_org_games_played2', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_goals_per_game2', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_penalties_per_game2', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_points_per_game2', ['org_id', 'points_per_game'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skater_org_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_org_points_per_game2')
        batch_op.drop_index('idx_org_penalties_per_game2')
        batch_op.drop_index('idx_org_goals_per_game2')
        batch_op.drop_index('idx_org_games_played2')
        batch_op.drop_index('idx_org_assists_per_game2')

    op.drop_table('skater_org_stats')
    # ### end Alembic commands ###
