"""Add daily/weekly classes and percentiles for each data field

Revision ID: 7f541e4b0bed
Revises: 65d87aa77dfe
Create Date: 2024-12-25 00:47:45.510595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f541e4b0bed'
down_revision = '65d87aa77dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_stats_daily_goalie',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_percentile', sa.Float(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_daily_uc_goalie1')
    )
    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_org_daily_games_played_goalie1', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_daily_goals_allowed1', ['org_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_org_daily_goals_allowed_per_game1', ['org_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_org_daily_save_percentage1', ['org_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_org_daily_shots_faced1', ['org_id', 'shots_faced'], unique=False)

    op.create_table('org_stats_daily_human',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_total', sa.Integer(), nullable=True),
    sa.Column('games_total_percentile', sa.Float(), nullable=True),
    sa.Column('games_skater', sa.Integer(), nullable=True),
    sa.Column('games_skater_percentile', sa.Float(), nullable=True),
    sa.Column('games_referee', sa.Integer(), nullable=True),
    sa.Column('games_referee_percentile', sa.Float(), nullable=True),
    sa.Column('games_scorekeeper', sa.Integer(), nullable=True),
    sa.Column('games_scorekeeper_percentile', sa.Float(), nullable=True),
    sa.Column('games_goalie', sa.Integer(), nullable=True),
    sa.Column('games_goalie_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_daily_stats_uc1')
    )
    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.create_index('idx_org_daily_games_goalie1', ['org_id', 'games_goalie'], unique=False)
        batch_op.create_index('idx_org_daily_games_referee1', ['org_id', 'games_referee'], unique=False)
        batch_op.create_index('idx_org_daily_games_scorekeeper1', ['org_id', 'games_scorekeeper'], unique=False)
        batch_op.create_index('idx_org_daily_games_skater1', ['org_id', 'games_skater'], unique=False)
        batch_op.create_index('idx_org_daily_games_total1', ['org_id', 'games_total'], unique=False)

    op.create_table('org_stats_daily_referee',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_reffed', sa.Integer(), nullable=True),
    sa.Column('games_reffed_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_given', sa.Integer(), nullable=True),
    sa.Column('penalties_given_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('gm_given', sa.Integer(), nullable=True),
    sa.Column('gm_given_percentile', sa.Float(), nullable=True),
    sa.Column('gm_per_game', sa.Float(), nullable=True),
    sa.Column('gm_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_daily_uc_referee1')
    )
    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.create_index('idx_org_daily_games_reffed1', ['org_id', 'games_reffed'], unique=False)
        batch_op.create_index('idx_org_daily_gm_given1', ['org_id', 'gm_given'], unique=False)
        batch_op.create_index('idx_org_daily_gm_per_game1', ['org_id', 'gm_per_game'], unique=False)
        batch_op.create_index('idx_org_daily_penalties_given1', ['org_id', 'penalties_given'], unique=False)
        batch_op.create_index('idx_org_daily_penalties_per_game1', ['org_id', 'penalties_per_game'], unique=False)

    op.create_table('org_stats_daily_scorekeeper',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_recorded', sa.Integer(), nullable=True),
    sa.Column('games_recorded_percentile', sa.Float(), nullable=True),
    sa.Column('sog_given', sa.Integer(), nullable=True),
    sa.Column('sog_given_percentile', sa.Float(), nullable=True),
    sa.Column('sog_per_game', sa.Float(), nullable=True),
    sa.Column('sog_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_daily_uc_scorekeeper1')
    )
    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_org_daily_games_recorded1', ['org_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_org_daily_sog_given1', ['org_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_org_daily_sog_per_game1', ['org_id', 'sog_per_game'], unique=False)

    op.create_table('org_stats_daily_skater',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_percentile', sa.Float(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('assists_percentile', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_percentile', sa.Float(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalties_percentile', sa.Float(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('goals_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_daily_uc_skater1')
    )
    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.create_index('idx_org_daily_assists_per_game3', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_org_daily_games_played3', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_daily_goals_per_game3', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_daily_penalties_per_game3', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_daily_points_per_game3', ['org_id', 'points_per_game'], unique=False)

    op.create_table('org_stats_weekly_goalie',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_percentile', sa.Float(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_weekly_uc_goalie1')
    )
    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_org_weekly_games_played_goalie1', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_weekly_goals_allowed1', ['org_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_org_weekly_goals_allowed_per_game1', ['org_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_org_weekly_save_percentage1', ['org_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_org_weekly_shots_faced1', ['org_id', 'shots_faced'], unique=False)

    op.create_table('org_stats_weekly_human',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_total', sa.Integer(), nullable=True),
    sa.Column('games_total_percentile', sa.Float(), nullable=True),
    sa.Column('games_skater', sa.Integer(), nullable=True),
    sa.Column('games_skater_percentile', sa.Float(), nullable=True),
    sa.Column('games_referee', sa.Integer(), nullable=True),
    sa.Column('games_referee_percentile', sa.Float(), nullable=True),
    sa.Column('games_scorekeeper', sa.Integer(), nullable=True),
    sa.Column('games_scorekeeper_percentile', sa.Float(), nullable=True),
    sa.Column('games_goalie', sa.Integer(), nullable=True),
    sa.Column('games_goalie_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_weekly_stats_uc1')
    )
    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.create_index('idx_org_weekly_games_goalie1', ['org_id', 'games_goalie'], unique=False)
        batch_op.create_index('idx_org_weekly_games_referee1', ['org_id', 'games_referee'], unique=False)
        batch_op.create_index('idx_org_weekly_games_scorekeeper1', ['org_id', 'games_scorekeeper'], unique=False)
        batch_op.create_index('idx_org_weekly_games_skater1', ['org_id', 'games_skater'], unique=False)
        batch_op.create_index('idx_org_weekly_games_total1', ['org_id', 'games_total'], unique=False)

    op.create_table('org_stats_weekly_referee',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_reffed', sa.Integer(), nullable=True),
    sa.Column('games_reffed_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_given', sa.Integer(), nullable=True),
    sa.Column('penalties_given_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('gm_given', sa.Integer(), nullable=True),
    sa.Column('gm_given_percentile', sa.Float(), nullable=True),
    sa.Column('gm_per_game', sa.Float(), nullable=True),
    sa.Column('gm_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_weekly_uc_referee1')
    )
    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.create_index('idx_org_weekly_games_reffed1', ['org_id', 'games_reffed'], unique=False)
        batch_op.create_index('idx_org_weekly_gm_given1', ['org_id', 'gm_given'], unique=False)
        batch_op.create_index('idx_org_weekly_gm_per_game1', ['org_id', 'gm_per_game'], unique=False)
        batch_op.create_index('idx_org_weekly_penalties_given1', ['org_id', 'penalties_given'], unique=False)
        batch_op.create_index('idx_org_weekly_penalties_per_game1', ['org_id', 'penalties_per_game'], unique=False)

    op.create_table('org_stats_weekly_scorekeeper',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_recorded', sa.Integer(), nullable=True),
    sa.Column('games_recorded_percentile', sa.Float(), nullable=True),
    sa.Column('sog_given', sa.Integer(), nullable=True),
    sa.Column('sog_given_percentile', sa.Float(), nullable=True),
    sa.Column('sog_per_game', sa.Float(), nullable=True),
    sa.Column('sog_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_weekly_uc_scorekeeper1')
    )
    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_org_weekly_games_recorded1', ['org_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_org_weekly_sog_given1', ['org_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_org_weekly_sog_per_game1', ['org_id', 'sog_per_game'], unique=False)

    op.create_table('org_stats_weekly_skater',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_percentile', sa.Float(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('assists_percentile', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_percentile', sa.Float(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalties_percentile', sa.Float(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('goals_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_weekly_uc_skater1')
    )
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.create_index('idx_org_weekly_assists_per_game3', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_org_weekly_games_played3', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_weekly_goals_per_game3', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_weekly_penalties_per_game3', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_weekly_points_per_game3', ['org_id', 'points_per_game'], unique=False)

    op.create_table('division_stats_daily_goalie',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_percentile', sa.Float(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_daily_uc_goalie1')
    )
    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_division_daily_games_played_goalie1', ['division_id', 'games_played'], unique=False)
        batch_op.create_index('idx_division_daily_goals_allowed1', ['division_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_division_daily_goals_allowed_per_game1', ['division_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_save_percentage1', ['division_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_division_daily_shots_faced1', ['division_id', 'shots_faced'], unique=False)

    op.create_table('division_stats_daily_human',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_total', sa.Integer(), nullable=True),
    sa.Column('games_total_percentile', sa.Float(), nullable=True),
    sa.Column('games_skater', sa.Integer(), nullable=True),
    sa.Column('games_skater_percentile', sa.Float(), nullable=True),
    sa.Column('games_referee', sa.Integer(), nullable=True),
    sa.Column('games_referee_percentile', sa.Float(), nullable=True),
    sa.Column('games_scorekeeper', sa.Integer(), nullable=True),
    sa.Column('games_scorekeeper_percentile', sa.Float(), nullable=True),
    sa.Column('games_goalie', sa.Integer(), nullable=True),
    sa.Column('games_goalie_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_daily_stats_uc1')
    )
    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.create_index('idx_division_daily_games_goalie1', ['division_id', 'games_goalie'], unique=False)
        batch_op.create_index('idx_division_daily_games_referee1', ['division_id', 'games_referee'], unique=False)
        batch_op.create_index('idx_division_daily_games_scorekeeper1', ['division_id', 'games_scorekeeper'], unique=False)
        batch_op.create_index('idx_division_daily_games_skater1', ['division_id', 'games_skater'], unique=False)
        batch_op.create_index('idx_division_daily_games_total1', ['division_id', 'games_total'], unique=False)

    op.create_table('division_stats_daily_referee',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_reffed', sa.Integer(), nullable=True),
    sa.Column('games_reffed_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_given', sa.Integer(), nullable=True),
    sa.Column('penalties_given_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('gm_given', sa.Integer(), nullable=True),
    sa.Column('gm_given_percentile', sa.Float(), nullable=True),
    sa.Column('gm_per_game', sa.Float(), nullable=True),
    sa.Column('gm_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_daily_uc_referee1')
    )
    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.create_index('idx_division_daily_games_reffed1', ['division_id', 'games_reffed'], unique=False)
        batch_op.create_index('idx_division_daily_gm_given1', ['division_id', 'gm_given'], unique=False)
        batch_op.create_index('idx_division_daily_gm_per_game1', ['division_id', 'gm_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_penalties_given1', ['division_id', 'penalties_given'], unique=False)
        batch_op.create_index('idx_division_daily_penalties_per_game1', ['division_id', 'penalties_per_game'], unique=False)

    op.create_table('division_stats_daily_scorekeeper',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_recorded', sa.Integer(), nullable=True),
    sa.Column('games_recorded_percentile', sa.Float(), nullable=True),
    sa.Column('sog_given', sa.Integer(), nullable=True),
    sa.Column('sog_given_percentile', sa.Float(), nullable=True),
    sa.Column('sog_per_game', sa.Float(), nullable=True),
    sa.Column('sog_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_daily_uc_scorekeeper1')
    )
    with op.batch_alter_table('division_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_division_daily_games_recorded1', ['division_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_division_daily_sog_given1', ['division_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_division_daily_sog_per_game1', ['division_id', 'sog_per_game'], unique=False)

    op.create_table('division_stats_daily_skater',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_percentile', sa.Float(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('assists_percentile', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_percentile', sa.Float(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalties_percentile', sa.Float(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('goals_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_daily_uc_skater1')
    )
    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.create_index('idx_division_daily_assists_per_game3', ['division_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_games_played3', ['division_id', 'games_played'], unique=False)
        batch_op.create_index('idx_division_daily_goals_per_game3', ['division_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_penalties_per_game3', ['division_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_points_per_game3', ['division_id', 'points_per_game'], unique=False)

    op.create_table('division_stats_weekly_goalie',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_percentile', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_percentile', sa.Float(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_weekly_uc_goalie1')
    )
    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_division_weekly_games_played_goalie1', ['division_id', 'games_played'], unique=False)
        batch_op.create_index('idx_division_weekly_goals_allowed1', ['division_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_division_weekly_goals_allowed_per_game1', ['division_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_save_percentage1', ['division_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_division_weekly_shots_faced1', ['division_id', 'shots_faced'], unique=False)

    op.create_table('division_stats_weekly_human',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_total', sa.Integer(), nullable=True),
    sa.Column('games_total_percentile', sa.Float(), nullable=True),
    sa.Column('games_skater', sa.Integer(), nullable=True),
    sa.Column('games_skater_percentile', sa.Float(), nullable=True),
    sa.Column('games_referee', sa.Integer(), nullable=True),
    sa.Column('games_referee_percentile', sa.Float(), nullable=True),
    sa.Column('games_scorekeeper', sa.Integer(), nullable=True),
    sa.Column('games_scorekeeper_percentile', sa.Float(), nullable=True),
    sa.Column('games_goalie', sa.Integer(), nullable=True),
    sa.Column('games_goalie_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_weekly_stats_uc1')
    )
    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.create_index('idx_division_weekly_games_goalie1', ['division_id', 'games_goalie'], unique=False)
        batch_op.create_index('idx_division_weekly_games_referee1', ['division_id', 'games_referee'], unique=False)
        batch_op.create_index('idx_division_weekly_games_scorekeeper1', ['division_id', 'games_scorekeeper'], unique=False)
        batch_op.create_index('idx_division_weekly_games_skater1', ['division_id', 'games_skater'], unique=False)
        batch_op.create_index('idx_division_weekly_games_total1', ['division_id', 'games_total'], unique=False)

    op.create_table('division_stats_weekly_referee',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_reffed', sa.Integer(), nullable=True),
    sa.Column('games_reffed_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_given', sa.Integer(), nullable=True),
    sa.Column('penalties_given_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('gm_given', sa.Integer(), nullable=True),
    sa.Column('gm_given_percentile', sa.Float(), nullable=True),
    sa.Column('gm_per_game', sa.Float(), nullable=True),
    sa.Column('gm_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_weekly_uc_referee1')
    )
    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.create_index('idx_division_weekly_games_reffed1', ['division_id', 'games_reffed'], unique=False)
        batch_op.create_index('idx_division_weekly_gm_given1', ['division_id', 'gm_given'], unique=False)
        batch_op.create_index('idx_division_weekly_gm_per_game1', ['division_id', 'gm_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_penalties_given1', ['division_id', 'penalties_given'], unique=False)
        batch_op.create_index('idx_division_weekly_penalties_per_game1', ['division_id', 'penalties_per_game'], unique=False)

    op.create_table('division_stats_weekly_scorekeeper',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_recorded', sa.Integer(), nullable=True),
    sa.Column('games_recorded_percentile', sa.Float(), nullable=True),
    sa.Column('sog_given', sa.Integer(), nullable=True),
    sa.Column('sog_given_percentile', sa.Float(), nullable=True),
    sa.Column('sog_per_game', sa.Float(), nullable=True),
    sa.Column('sog_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_weekly_uc_scorekeeper1')
    )
    with op.batch_alter_table('division_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_division_weekly_games_recorded1', ['division_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_division_weekly_sog_given1', ['division_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_division_weekly_sog_per_game1', ['division_id', 'sog_per_game'], unique=False)

    op.create_table('division_stats_weekly_skater',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_percentile', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_percentile', sa.Float(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('assists_percentile', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_percentile', sa.Float(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalties_percentile', sa.Float(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('goals_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game_percentile', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_weekly_uc_skater1')
    )
    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.create_index('idx_division_weekly_assists_per_game3', ['division_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_games_played3', ['division_id', 'games_played'], unique=False)
        batch_op.create_index('idx_division_weekly_goals_per_game3', ['division_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_penalties_per_game3', ['division_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_points_per_game3', ['division_id', 'points_per_game'], unique=False)

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_played_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_allowed_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_allowed_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shots_faced_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('save_percentage_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_total_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_skater_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_referee_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_scorekeeper_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_goalie_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_reffed_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_given_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_given_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_per_game_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_recorded_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sog_given_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sog_per_game_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_played_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assists_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('points_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('points_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assists_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_played_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_allowed_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_allowed_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shots_faced_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('save_percentage_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_total_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_skater_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_referee_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_scorekeeper_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_goalie_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_reffed_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_given_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_given_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_per_game_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_recorded_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sog_given_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sog_per_game_percentile', sa.Float(), nullable=True))

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_played_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assists_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('points_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('points_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('assists_per_game_percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalties_per_game_percentile', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('penalties_per_game_percentile')
        batch_op.drop_column('assists_per_game_percentile')
        batch_op.drop_column('points_per_game_percentile')
        batch_op.drop_column('goals_per_game_percentile')
        batch_op.drop_column('penalties_percentile')
        batch_op.drop_column('points_percentile')
        batch_op.drop_column('assists_percentile')
        batch_op.drop_column('goals_percentile')
        batch_op.drop_column('games_played_percentile')

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('sog_per_game_percentile')
        batch_op.drop_column('sog_given_percentile')
        batch_op.drop_column('games_recorded_percentile')

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('gm_per_game_percentile')
        batch_op.drop_column('gm_given_percentile')
        batch_op.drop_column('penalties_per_game_percentile')
        batch_op.drop_column('penalties_given_percentile')
        batch_op.drop_column('games_reffed_percentile')

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.drop_column('games_goalie_percentile')
        batch_op.drop_column('games_scorekeeper_percentile')
        batch_op.drop_column('games_referee_percentile')
        batch_op.drop_column('games_skater_percentile')
        batch_op.drop_column('games_total_percentile')

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('save_percentage_percentile')
        batch_op.drop_column('shots_faced_percentile')
        batch_op.drop_column('goals_allowed_per_game_percentile')
        batch_op.drop_column('goals_allowed_percentile')
        batch_op.drop_column('games_played_percentile')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('penalties_per_game_percentile')
        batch_op.drop_column('assists_per_game_percentile')
        batch_op.drop_column('points_per_game_percentile')
        batch_op.drop_column('goals_per_game_percentile')
        batch_op.drop_column('penalties_percentile')
        batch_op.drop_column('points_percentile')
        batch_op.drop_column('assists_percentile')
        batch_op.drop_column('goals_percentile')
        batch_op.drop_column('games_played_percentile')

    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('sog_per_game_percentile')
        batch_op.drop_column('sog_given_percentile')
        batch_op.drop_column('games_recorded_percentile')

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('gm_per_game_percentile')
        batch_op.drop_column('gm_given_percentile')
        batch_op.drop_column('penalties_per_game_percentile')
        batch_op.drop_column('penalties_given_percentile')
        batch_op.drop_column('games_reffed_percentile')

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.drop_column('games_goalie_percentile')
        batch_op.drop_column('games_scorekeeper_percentile')
        batch_op.drop_column('games_referee_percentile')
        batch_op.drop_column('games_skater_percentile')
        batch_op.drop_column('games_total_percentile')

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('save_percentage_percentile')
        batch_op.drop_column('shots_faced_percentile')
        batch_op.drop_column('goals_allowed_per_game_percentile')
        batch_op.drop_column('goals_allowed_percentile')
        batch_op.drop_column('games_played_percentile')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_points_per_game3')
        batch_op.drop_index('idx_division_weekly_penalties_per_game3')
        batch_op.drop_index('idx_division_weekly_goals_per_game3')
        batch_op.drop_index('idx_division_weekly_games_played3')
        batch_op.drop_index('idx_division_weekly_assists_per_game3')

    op.drop_table('division_stats_weekly_skater')
    with op.batch_alter_table('division_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_sog_per_game1')
        batch_op.drop_index('idx_division_weekly_sog_given1')
        batch_op.drop_index('idx_division_weekly_games_recorded1')

    op.drop_table('division_stats_weekly_scorekeeper')
    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_penalties_per_game1')
        batch_op.drop_index('idx_division_weekly_penalties_given1')
        batch_op.drop_index('idx_division_weekly_gm_per_game1')
        batch_op.drop_index('idx_division_weekly_gm_given1')
        batch_op.drop_index('idx_division_weekly_games_reffed1')

    op.drop_table('division_stats_weekly_referee')
    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_games_total1')
        batch_op.drop_index('idx_division_weekly_games_skater1')
        batch_op.drop_index('idx_division_weekly_games_scorekeeper1')
        batch_op.drop_index('idx_division_weekly_games_referee1')
        batch_op.drop_index('idx_division_weekly_games_goalie1')

    op.drop_table('division_stats_weekly_human')
    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_shots_faced1')
        batch_op.drop_index('idx_division_weekly_save_percentage1')
        batch_op.drop_index('idx_division_weekly_goals_allowed_per_game1')
        batch_op.drop_index('idx_division_weekly_goals_allowed1')
        batch_op.drop_index('idx_division_weekly_games_played_goalie1')

    op.drop_table('division_stats_weekly_goalie')
    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_points_per_game3')
        batch_op.drop_index('idx_division_daily_penalties_per_game3')
        batch_op.drop_index('idx_division_daily_goals_per_game3')
        batch_op.drop_index('idx_division_daily_games_played3')
        batch_op.drop_index('idx_division_daily_assists_per_game3')

    op.drop_table('division_stats_daily_skater')
    with op.batch_alter_table('division_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_sog_per_game1')
        batch_op.drop_index('idx_division_daily_sog_given1')
        batch_op.drop_index('idx_division_daily_games_recorded1')

    op.drop_table('division_stats_daily_scorekeeper')
    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_penalties_per_game1')
        batch_op.drop_index('idx_division_daily_penalties_given1')
        batch_op.drop_index('idx_division_daily_gm_per_game1')
        batch_op.drop_index('idx_division_daily_gm_given1')
        batch_op.drop_index('idx_division_daily_games_reffed1')

    op.drop_table('division_stats_daily_referee')
    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_games_total1')
        batch_op.drop_index('idx_division_daily_games_skater1')
        batch_op.drop_index('idx_division_daily_games_scorekeeper1')
        batch_op.drop_index('idx_division_daily_games_referee1')
        batch_op.drop_index('idx_division_daily_games_goalie1')

    op.drop_table('division_stats_daily_human')
    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_shots_faced1')
        batch_op.drop_index('idx_division_daily_save_percentage1')
        batch_op.drop_index('idx_division_daily_goals_allowed_per_game1')
        batch_op.drop_index('idx_division_daily_goals_allowed1')
        batch_op.drop_index('idx_division_daily_games_played_goalie1')

    op.drop_table('division_stats_daily_goalie')
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_points_per_game3')
        batch_op.drop_index('idx_org_weekly_penalties_per_game3')
        batch_op.drop_index('idx_org_weekly_goals_per_game3')
        batch_op.drop_index('idx_org_weekly_games_played3')
        batch_op.drop_index('idx_org_weekly_assists_per_game3')

    op.drop_table('org_stats_weekly_skater')
    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_sog_per_game1')
        batch_op.drop_index('idx_org_weekly_sog_given1')
        batch_op.drop_index('idx_org_weekly_games_recorded1')

    op.drop_table('org_stats_weekly_scorekeeper')
    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_penalties_per_game1')
        batch_op.drop_index('idx_org_weekly_penalties_given1')
        batch_op.drop_index('idx_org_weekly_gm_per_game1')
        batch_op.drop_index('idx_org_weekly_gm_given1')
        batch_op.drop_index('idx_org_weekly_games_reffed1')

    op.drop_table('org_stats_weekly_referee')
    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_games_total1')
        batch_op.drop_index('idx_org_weekly_games_skater1')
        batch_op.drop_index('idx_org_weekly_games_scorekeeper1')
        batch_op.drop_index('idx_org_weekly_games_referee1')
        batch_op.drop_index('idx_org_weekly_games_goalie1')

    op.drop_table('org_stats_weekly_human')
    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_shots_faced1')
        batch_op.drop_index('idx_org_weekly_save_percentage1')
        batch_op.drop_index('idx_org_weekly_goals_allowed_per_game1')
        batch_op.drop_index('idx_org_weekly_goals_allowed1')
        batch_op.drop_index('idx_org_weekly_games_played_goalie1')

    op.drop_table('org_stats_weekly_goalie')
    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_points_per_game3')
        batch_op.drop_index('idx_org_daily_penalties_per_game3')
        batch_op.drop_index('idx_org_daily_goals_per_game3')
        batch_op.drop_index('idx_org_daily_games_played3')
        batch_op.drop_index('idx_org_daily_assists_per_game3')

    op.drop_table('org_stats_daily_skater')
    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_sog_per_game1')
        batch_op.drop_index('idx_org_daily_sog_given1')
        batch_op.drop_index('idx_org_daily_games_recorded1')

    op.drop_table('org_stats_daily_scorekeeper')
    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_penalties_per_game1')
        batch_op.drop_index('idx_org_daily_penalties_given1')
        batch_op.drop_index('idx_org_daily_gm_per_game1')
        batch_op.drop_index('idx_org_daily_gm_given1')
        batch_op.drop_index('idx_org_daily_games_reffed1')

    op.drop_table('org_stats_daily_referee')
    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_games_total1')
        batch_op.drop_index('idx_org_daily_games_skater1')
        batch_op.drop_index('idx_org_daily_games_scorekeeper1')
        batch_op.drop_index('idx_org_daily_games_referee1')
        batch_op.drop_index('idx_org_daily_games_goalie1')

    op.drop_table('org_stats_daily_human')
    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_shots_faced1')
        batch_op.drop_index('idx_org_daily_save_percentage1')
        batch_op.drop_index('idx_org_daily_goals_allowed_per_game1')
        batch_op.drop_index('idx_org_daily_goals_allowed1')
        batch_op.drop_index('idx_org_daily_games_played_goalie1')

    op.drop_table('org_stats_daily_goalie')
    # ### end Alembic commands ###
