"""skater_org_stats table to use

Revision ID: 892ffc672d59
Revises: f81a0e51ad24
Create Date: 2024-12-21 18:52:03.635887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892ffc672d59'
down_revision = 'f81a0e51ad24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skater_org_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_uc_skater')
    )
    with op.batch_alter_table('skater_org_stats', schema=None) as batch_op:
        batch_op.create_index('idx_org_assists_per_game2', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_org_games_played2', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_goals_per_game2', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_penalties_per_game2', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_points_per_game2', ['org_id', 'points_per_game'], unique=False)

    with op.batch_alter_table('goalie_org_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_org_games_played_goalie')
        batch_op.drop_index('idx_org_goals_allowed')
        batch_op.drop_index('idx_org_goals_allowed_per_game')
        batch_op.drop_index('idx_org_save_percentage')
        batch_op.drop_index('idx_org_shots_faced')

    op.drop_table('goalie_org_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie_org_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('human_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_played', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_allowed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_allowed_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shots_faced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('save_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], name='goalie_org_stats_human_id_fkey'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='goalie_org_stats_org_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goalie_org_stats_pkey'),
    sa.UniqueConstraint('human_id', 'org_id', name='_goalie_org_uc')
    )
    with op.batch_alter_table('goalie_org_stats', schema=None) as batch_op:
        batch_op.create_index('idx_org_shots_faced', ['org_id', 'shots_faced'], unique=False)
        batch_op.create_index('idx_org_save_percentage', ['org_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_org_goals_allowed_per_game', ['org_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_org_goals_allowed', ['org_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_org_games_played_goalie', ['org_id', 'games_played'], unique=False)

    with op.batch_alter_table('skater_org_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_org_points_per_game2')
        batch_op.drop_index('idx_org_penalties_per_game2')
        batch_op.drop_index('idx_org_goals_per_game2')
        batch_op.drop_index('idx_org_games_played2')
        batch_op.drop_index('idx_org_assists_per_game2')

    op.drop_table('skater_org_stats')
    # ### end Alembic commands ###
