"""BaseStatsGoalie and DivisionStats

Revision ID: b3ccc8ac2eeb
Revises: 7cc11e8eec68
Create Date: 2024-12-22 15:58:32.092214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ccc8ac2eeb'
down_revision = '7cc11e8eec68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division_stats_goalie',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_uc_goalie1')
    )
    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_division_games_played_goalie1', ['division_id', 'games_played'], unique=False)
        batch_op.create_index('idx_division_goals_allowed1', ['division_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_division_goals_allowed_per_game1', ['division_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_division_save_percentage1', ['division_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_division_shots_faced1', ['division_id', 'shots_faced'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_division_shots_faced1')
        batch_op.drop_index('idx_division_save_percentage1')
        batch_op.drop_index('idx_division_goals_allowed_per_game1')
        batch_op.drop_index('idx_division_goals_allowed1')
        batch_op.drop_index('idx_division_games_played_goalie1')

    op.drop_table('division_stats_goalie')
    # ### end Alembic commands ###
