"""org_id not null in all remaining classes

Revision ID: c26c5fb00f6b
Revises: 449ae96da2e7
Create Date: 2024-12-15 12:55:09.910005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26c5fb00f6b'
down_revision = '449ae96da2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('humans_in_tts', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('levels_monthly', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('org_league_season_dates', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teams_in_tts', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_in_tts', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('org_league_season_dates', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('levels_monthly', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('humans_in_tts', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
