"""new data in OrgStatsHuman

Revision ID: d3860a78c158
Revises: 892ffc672d59
Create Date: 2024-12-21 18:55:18.989145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3860a78c158'
down_revision = '892ffc672d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_org_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_skater', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_referee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_scorekeeper', sa.Integer(), nullable=True))
        batch_op.drop_constraint('_human_org_uc', type_='unique')
        batch_op.drop_index('idx_org_assists_per_game1')
        batch_op.drop_index('idx_org_games_played1')
        batch_op.drop_index('idx_org_goals_per_game1')
        batch_op.drop_index('idx_org_penalties_per_game1')
        batch_op.drop_index('idx_org_points_per_game1')
        batch_op.create_unique_constraint('_human_org_stats_uc', ['human_id', 'org_id'])
        batch_op.create_index('idx_org_games_referee', ['org_id', 'games_referee'], unique=False)
        batch_op.create_index('idx_org_games_scorekeeper', ['org_id', 'games_scorekeeper'], unique=False)
        batch_op.create_index('idx_org_games_skater', ['org_id', 'games_skater'], unique=False)
        batch_op.create_index('idx_org_games_total', ['org_id', 'games_total'], unique=False)
        batch_op.drop_column('penalties')
        batch_op.drop_column('assists_per_game')
        batch_op.drop_column('goals_per_game')
        batch_op.drop_column('assists')
        batch_op.drop_column('goals')
        batch_op.drop_column('points_per_game')
        batch_op.drop_column('points')
        batch_op.drop_column('games_played')
        batch_op.drop_column('penalties_per_game')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_org_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalties_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('games_played', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('points_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goals_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assists_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_org_games_total')
        batch_op.drop_index('idx_org_games_skater')
        batch_op.drop_index('idx_org_games_scorekeeper')
        batch_op.drop_index('idx_org_games_referee')
        batch_op.drop_constraint('_human_org_stats_uc', type_='unique')
        batch_op.create_index('idx_org_points_per_game1', ['org_id', 'points_per_game'], unique=False)
        batch_op.create_index('idx_org_penalties_per_game1', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_goals_per_game1', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_games_played1', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_assists_per_game1', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_unique_constraint('_human_org_uc', ['human_id', 'org_id'])
        batch_op.drop_column('games_scorekeeper')
        batch_op.drop_column('games_referee')
        batch_op.drop_column('games_skater')
        batch_op.drop_column('games_total')

    # ### end Alembic commands ###
