"""remove org_id from NamesInTeams

Revision ID: d89205a1ad44
Revises: 1af00956dd02
Create Date: 2024-12-11 14:08:56.398345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89205a1ad44'
down_revision = '1af00956dd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('names_in_teams', schema=None) as batch_op:
        batch_op.drop_constraint('_org_team_name_uc', type_='unique')
        batch_op.create_unique_constraint('_team_name_uc', ['team_id', 'first_name', 'middle_name', 'last_name'])
        batch_op.drop_constraint('names_in_teams_org_id_fkey', type_='foreignkey')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('names_in_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('names_in_teams_org_id_fkey', 'organizations', ['org_id'], ['id'])
        batch_op.drop_constraint('_team_name_uc', type_='unique')
        batch_op.create_unique_constraint('_org_team_name_uc', ['org_id', 'team_id', 'first_name', 'middle_name', 'last_name'])

    # ### end Alembic commands ###
