"""add games_goalie in  OrgStatsHuman

Revision ID: d9c91459878a
Revises: d3860a78c158
Create Date: 2024-12-21 19:08:40.589203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c91459878a'
down_revision = 'd3860a78c158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_org_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_goalie', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_games_goalie', ['org_id', 'games_goalie'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_org_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_org_games_goalie')
        batch_op.drop_column('games_goalie')

    # ### end Alembic commands ###
