"""Add OrgStatsGoalie again

Revision ID: dbde5306c617
Revises: d9c91459878a
Create Date: 2024-12-22 15:11:09.066008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbde5306c617'
down_revision = 'd9c91459878a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie_org_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'org_id', name='_human_org_uc_goalie')
    )
    with op.batch_alter_table('goalie_org_stats', schema=None) as batch_op:
        batch_op.create_index('idx_org_games_played_goalie', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_goals_allowed', ['org_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_org_goals_allowed_per_game', ['org_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_org_save_percentage', ['org_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_org_shots_faced', ['org_id', 'shots_faced'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goalie_org_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_org_shots_faced')
        batch_op.drop_index('idx_org_save_percentage')
        batch_op.drop_index('idx_org_goals_allowed_per_game')
        batch_op.drop_index('idx_org_goals_allowed')
        batch_op.drop_index('idx_org_games_played_goalie')

    op.drop_table('goalie_org_stats')
    # ### end Alembic commands ###
