"""add org to Season

Revision ID: dddefad7b6d2
Revises: 56b676f80965
Create Date: 2024-12-11 12:25:57.602261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddefad7b6d2'
down_revision = '56b676f80965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('_league_season_uc', type_='unique')
        batch_op.create_unique_constraint('_org_league_season_uc', ['org_id', 'league_number', 'season_number'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_org_league_season_uc', type_='unique')
        batch_op.create_unique_constraint('_league_season_uc', ['league_number', 'season_number'])
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
