"""Remove org from DivisionStatsHuman , add OrgStatsHuman

Revision ID: e5c82c1106e0
Revises: 244c8fb749a0
Create Date: 2024-12-21 15:59:08.538027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c82c1106e0'
down_revision = '244c8fb749a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_division_stats', schema=None) as batch_op:
        batch_op.drop_constraint('_org_human_division_uc', type_='unique')
        batch_op.drop_index('idx_org_assists_per_game')
        batch_op.drop_index('idx_org_games_played')
        batch_op.drop_index('idx_org_goals_per_game')
        batch_op.drop_index('idx_org_penalties_per_game')
        batch_op.drop_index('idx_org_points_per_game')
        batch_op.create_unique_constraint('_human_division_uc', ['human_id', 'division_id'])
        batch_op.create_index('idx_division_games_played', ['division_id', 'games_played'], unique=False)
        batch_op.drop_constraint('human_division_stats_org_id_fkey', type_='foreignkey')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_division_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('human_division_stats_org_id_fkey', 'organizations', ['org_id'], ['id'])
        batch_op.drop_index('idx_division_games_played')
        batch_op.drop_constraint('_human_division_uc', type_='unique')
        batch_op.create_index('idx_org_points_per_game', ['org_id', 'points_per_game'], unique=False)
        batch_op.create_index('idx_org_penalties_per_game', ['org_id', 'penalties_per_game'], unique=False)
        batch_op.create_index('idx_org_goals_per_game', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_games_played', ['org_id', 'games_played'], unique=False)
        batch_op.create_index('idx_org_assists_per_game', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_unique_constraint('_org_human_division_uc', ['org_id', 'human_id', 'division_id'])

    # ### end Alembic commands ###
