"""add org to HumanInTTS

Revision ID: f490138b9259
Revises: 2d83134aeef0
Create Date: 2024-12-11 12:20:39.376321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f490138b9259'
down_revision = '2d83134aeef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humans_in_tts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('_human_tts_uc', type_='unique')
        batch_op.create_unique_constraint('_org_tts_uc', ['org_id', 'tts_id'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humans_in_tts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_org_tts_uc', type_='unique')
        batch_op.create_unique_constraint('_human_tts_uc', ['human_id', 'tts_id'])
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
